version: '2'

services:
  angular:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    volumes:
      - ./:/opt/project
      - /opt/project/node_modules # http://dchua.com/2016/02/07/getting-npm-packages-to-be-installed-with-docker-compose/
    ports:
      - "3000:3000"
